@echo off
echo Checking for processes on port 5173...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":5173" ^| find "LISTENING"') do (
    echo Killing process %%a on port 5173...
    taskkill /F /PID %%a >nul 2>&1
)
echo Starting development server...
npm run dev